added taskcat config, cfn-init logs/loggroup

diff --git a/quickstart-chainlink-node-master.yml b/quickstart-chainlink-node-master.yml
--- a/quickstart-chainlink-node-master.yml
+++ b/quickstart-chainlink-node-master.yml
@@ -18,7 +18,6 @@ Metadata:
           - PublicSubnet2CIDR
           - RemoteAccessCIDR
           - VPCTenancy
-          - SSLCertificate
       - Label:
           default: Amazon EC2 configuration
         Parameters:
@@ -45,6 +44,7 @@ Metadata:
           - ChainlinkNodeGUIPassword
           - EthereumNodeUrl
           - NodeWalletPassword
+          - SSLCertificateARN
       - Label:
           default: Aurora PostreSQL configuration
         Parameters:
@@ -82,8 +82,6 @@ Metadata:
         default: Allowed bastion external access CIDR
       VPCTenancy:
         default: VPC tenancy
-      SSLCertificate:
-        default: SSL certificate ARN
 
       # amazon ec2 config labels
       KeyPairName:
@@ -122,6 +120,8 @@ Metadata:
         default: Ethereum Node Websocket Url
       NodeWalletPassword:
         default: Chainlink Node Wallet Password
+      SSLCertificateARN:
+        default: SSL certificate ARN from AWS Certificate Manager
 
       # db config labels
       DBName:
@@ -200,10 +200,6 @@ Parameters:
       - dedicated
     Default: default
     Description: The allowed tenancy of instances launched into the VPC.
-    Type: String
-  SSLCertificate:
-    Description: 'ARN for the Certificate'
-    Default: ''
     Type: String
 
   # Amazon EC2 Configuration
@@ -334,6 +330,10 @@ Parameters:
     MaxLength: '32'
     MinLength: '9'
     NoEcho: 'True'
+    Type: String
+  SSLCertificateARN:
+    Description: 'ARN for the certificate created through AWS Certificate Manager'
+    Default: ''
     Type: String
 
   # PostreSQL DB Configuration
@@ -774,9 +774,37 @@ Resources:
       UserData:
         Fn::Base64: !Sub |
           #!/bin/bash -xe
-          # run cfn-init ec2-bootstrap
-          yum install -y aws-cfn-bootstrap
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource ChainlinkNodeLaunchConfiguration --configsets ec2_bootstrap --region ${AWS::Region}
+          # cfn fail functions
+          function cfn_fail
+          {
+            cfn-signal -e 1 --stack ${AWS::StackName} --region ${AWS::Region} --resource CordaInstance
+            exit 1
+          }
+          function cfn_success
+          {
+            cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource CordaInstance
+            exit 0
+          }
+          # install git and run cfn-bootstrap
+          yum install -y git
+          git clone https://github.com/aws-quickstart/quickstart-linux-utilities.git
+          cd /quickstart-linux-utilities
+          source quickstart-cfn-tools.source
+          qs_update-os || qs_err
+          qs_bootstrap_pip || qs_err
+          qs_aws-cfn-bootstrap || qs_err
+          # create cloudwatch log group
+          sed -i "s/__LOGGROUP__/${ChainlinkNodeInitLogGroup}/g" cloudwatch_logs.stub
+          # install cloudwatch - issue of failing to determine linux distribution on Amazon Linux 2 AMI
+          echo 'Amazon Linux AMI' > /etc/issue
+          qs_cloudwatch_install || qs_err
+          # debug cfn-init logs
+          qs_cloudwatch_tracklog /var/log/cfn-init.log
+          qs_cloudwatch_tracklog /var/log/cfn-init-cmd.log
+          # cfn-init bootstrap
+          cfn-init -v --stack ${AWS::StackName} --resource ChainlinkNodeLaunchConfiguration --configsets ec2_bootstrap --region ${AWS::Region}
+          cfn_fail
+          [ $(qs_status) == 0 ] && cfn_success || cfn_fail
 
   ChainlinkNodeInstanceProfile:
     Type: AWS::IAM::InstanceProfile
@@ -807,12 +835,29 @@ Resources:
               - Resource: '*'
                 Effect: Allow 
                 Action:
-                  - logs:CreateLogStream
-                  - logs:CreateLogGroup
-                  - logs:PutLogEvents
-                  - cloudwatch:PutMetricData
-                  - cloudwatch:GetMetricStatistics
-                  - cloudwatch:ListMetrics
+                  - 'logs:CreateLogStream'
+                  - 'logs:CreateLogGroup'
+                  - 'logs:PutLogEvents'
+                  - 'logs:DescribeLogStreams'
+              - Effect: Allow
+                Action:
+                  - 'cloudwatch:PutMetricData'
+                  - 'cloudwatch:GetMetricStatistics'
+                  - 'cloudwatch:ListMetrics'
+                Resource:
+                  - '*'
+              - Effect: Allow
+                Action:
+                  - 'ec2:DescribeInstances'
+                Resource: '*'
+              - Resource:
+                  - !Ref DBSecret
+                  - !Ref ApiSecret
+                  - !Ref WalletSecret
+                Effect: "Allow"
+                Action:
+                  - secretsmanager:GetSecretValue
+                  # - ssm:GetParameters
 
   # ChainlinkLogRole:
   #   Type: 'AWS::IAM::Role'
@@ -892,32 +937,44 @@ Resources:
     Properties:
       LoadBalancerArn: !Ref ChainlinkNodeELB
       Certificates: 
-        - CertificateArn: !Ref SSLCertificate
+        - CertificateArn: !Ref SSLCertificateARN
       DefaultActions:
         - Type: 'forward'
           TargetGroupArn: !Ref ChainlinkNodeTargetGroup
       Port: 443
       Protocol: 'HTTPS'
       SslPolicy: 'ELBSecurityPolicy-2016-08'
-  #Docker Logs to Cloudwatch
+  # Cloudwatch
   ChainlinkLogGroup:
     Type: 'AWS::Logs::LogGroup'
     Properties:
       LogGroupName: ChainlinkLogs
       RetentionInDays: 7
+  ChainlinkNodeInitLogGroup:
+    Type: 'AWS::Logs::LogGroup'
+    Properties:
+      LogGroupName: ChainlinkNodeInitLogGroup
+      RetentionInDays: 7
 
-  DatabaseCreds:
+  # Secrets
+  DBSecret:
     Type: 'AWS::SecretsManager::Secret'
     Properties:
-      Name: DatabaseCreds
-      Description: This secret credentials for DatabaseCreds
-      SecretString: !Sub '{"username":"${DBMasterUsername}","password":"${DBMasterUserPassword}"'
-  # DatabaseCreds:
-  #   Type: 'AWS::SecretsManager::Secret'
-  #   Properties:
-  #     Name: DatabaseCreds
-  #     Description: This secret credentials for DatabaseCreds
-  #     SecretString: !Sub '{"username":"${DBMasterUsername}","password":"${DBMasterUserPassword}"'
+      Name: DBSecret
+      Description: Secret password for PostgreSQL database.
+      SecretString: !Sub '{"psqlPwd":"${DBMasterUserPassword}"'
+  ApiSecret:
+    Type: 'AWS::SecretsManager::Secret'
+    Properties:
+      Name: ApiSecret
+      Description: Secret password for Chainlink node GUI
+      SecretString: !Sub '{"apiPwd":"${ChainlinkNodeGUIPassword}"'
+  WalletSecret:
+    Type: 'AWS::SecretsManager::Secret'
+    Properties:
+      Name: WalletSecret
+      Description: Secret password for Chainlink node wallet password
+      SecretString: !Sub '{"walletPwd":"${NodeWalletPassword}"'
 
   # DBSecrets:
   #   Type: AWS::SecretsManager::SecretTargetAttachment
diff --git a/test.yml b/test.yml
--- a/test.yml
+++ b/test.yml
@@ -502,41 +502,42 @@ Resources:
               configSets:
                 ec2_bootstrap:
                   - common-init
-                  - install-pkg
+                  # - set-latest-image
                   - create-env
                   - install-docker
               common-init:
                 commands:
                   01-store-chainnetwork-var:
-                    command: !Sub "echo 'chainNetwork=${BlockchainNetwork}' >> /etc/environment"
+                    command: !Sub echo 'chainNetwork=${BlockchainNetwork}' >> /etc/environment
                   02-store-blockchainrpc-var:
-                    command: !Sub "echo 'ethUrl=${EthereumNodeUrl}' >> /etc/environment"
+                    command: !Sub echo 'ethUrl=${EthereumNodeUrl}' >> /etc/environment
                   03-store-dbuser-var:
-                    command: !Sub "echo 'psqlUser=${DBMasterUsername}' >> /etc/environment"
+                    command: !Sub echo 'psqlUser=${DBMasterUsername}' >> /etc/environment
                   04-store-dbpwd-var:
-                    command: !Sub "echo 'psqlPwd=${DBMasterUserPassword}' >> /etc/environment"
+                    command: !Sub echo 'psqlPwd=${DBMasterUserPassword}' >> /etc/environment
                   05-store-dbhostname-var:
-                    command: !Sub "echo 'psqlHostname=${DBHostname}' >> /etc/environment"
+                    command: !Sub 
+                      - echo 'psqlHostname=${DBHostname}' >> /etc/environment
+                      - DBHostname: test
                   06-store-dbport-var:
-                    command: !Sub "echo 'psqlPort=${DBPort}' >> /etc/environment"
+                    command: !Sub echo 'psqlPort=${DBPort}' >> /etc/environment
                   07-store-dbname-var:
-                    command: !Sub "echo 'psqlDb=${DBName}' >> /etc/environment"
+                    command: !Sub echo 'psqlDb=${DBName}' >> /etc/environment
                   08-store-apiuser-var:
-                    command: !Sub "echo 'apiUser=${ChainlinkNodeGUIEmail}' >> /etc/environment"
+                    command: !Sub echo 'apiUser=${ChainlinkNodeGUIEmail}' >> /etc/environment
                   09-store-apipwd-var:
-                    command: !Sub "echo 'apiPwd=${ChainlinkNodeGUIPassword}' >> /etc/environment"
+                    command: !Sub echo 'apiPwd=${ChainlinkNodeGUIPassword}' >> /etc/environment
                   10-store-walletpwd-var:
-                    command: !Sub "echo 'walletPwd=${NodeWalletPassword}' >> /etc/environment"
+                    command: !Sub echo 'walletPwd=${NodeWalletPassword}' >> /etc/environment
                   11-create-chainlink-dir:
-                    command: "mkdir /home/ec2-user/.chainlink"
-                  12-set-latest-image:
-                    command: |
-                      "latestimage=$(curl -s -S "https://registry.hub.docker.com/v2/repositories/smartcontract/chainlink/tags/" | jq -r '."results"[]["name"]' | head -n 1"
-              install-pkg:
-                packages:
-                  yum:
-                    jq: []
-                    awscli: []
+                    command: mkdir /home/ec2-user/.chainlink
+              # set-latest-image:
+              #   packages:
+              #     yum:
+              #       jq: []
+              #   commands:
+              #     01-set-latest:
+              #       command: echo latestimage=$(curl -s -S "https://registry.hub.docker.com/v2/repositories/smartcontract/chainlink/tags/" | jq -r '."results"[]["name"]' | head -n 1) >> /etc/environment
               create-env:
                 packages:
                   yum:
@@ -545,7 +546,7 @@ Resources:
                   01-dl-script:
                     command:
                       wget -O test.sh https://raw.githubusercontent.com/dangitsdavid/test/main/test.sh
-                  02-script-permission:
+                  02-env-script-permission:
                     command:
                       chmod +x test.sh
                   03-create-env-file:
@@ -554,6 +555,7 @@ Resources:
               install-docker:
                 packages:
                   yum:
+                    jq: []
                     docker: []
                 services:
                   sysvinit:
@@ -565,7 +567,19 @@ Resources:
                     command: systemctl start docker
                   02-docker-for-ec2-user:
                     command: gpasswd -a ec2-user docker
-                  03-run-chainlink-docker:
+                  03-get-latest-script:
+                    command:
+                      wget -O getlatest.sh https://raw.githubusercontent.com/dangitsdavid/test/main/getlatest.sh
+                  04-getlatest-script-permission:
+                    command:
+                      chmod +x getlatest.sh
+                  05-get-latest-image:
+                    command:
+                      sudo bash getlatest.sh
+                  # 06-pull-latest-image:
+                  #   command:
+                  #     docker pull smartcontract/chainlink:$latestimage
+                  07-run-chainlink-docker:
                     command: |
                       cd /home/ec2-user/.chainlink && docker run \
                         --log-driver=awslogs \
@@ -595,7 +609,7 @@ Resources:
                         -e ETH_GAS_BUMP_WEI=7000000000 \
                         -e ETH_BALANCE_MONITOR_BLOCK_DELAY=3 \
                         -e ENABLE_BULLETPROOF_TX_MANAGER=true \
-                        smartcontract/chainlink:$latestimage local n \
+                        smartcontract/chainlink:0.10.8 local n \
                         -p ${walletPwd} \
                         -a ${apiUser} \
                         -a ${apiPwd}
@@ -615,10 +629,36 @@ Resources:
             DeleteOnTermination: true
       UserData:
         Fn::Base64: !Sub |
-          #!/bin/bash -x
-          # install and run cfn-boostrap
-          yum install -y aws-cfn-bootstrap
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource ChainlinkNodeLaunchConfiguration --configsets ec2_bootstrap --region ${AWS::Region}
+          #!/bin/bash -xe
+          # cfn fail functions
+          function cfn_fail
+          {
+            cfn-signal -e 1 --stack ${AWS::StackName} --region ${AWS::Region} --resource CordaInstance
+            exit 1
+          }
+          function cfn_success
+          {
+            cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource CordaInstance
+            exit 0
+          }
+          # install git and run cfn-bootstrap
+          yum install -y git
+          git clone https://github.com/aws-quickstart/quickstart-linux-utilities.git
+          cd /quickstart-linux-utilities
+          source quickstart-cfn-tools.source
+          qs_update-os || qs_err
+          qs_bootstrap_pip || qs_err
+          qs_aws-cfn-bootstrap || qs_err
+          # create cloudwatch log group
+          sed -i "s/__LOGGROUP__/${ChainlinkNodeInitLogGroup}/g" cloudwatch_logs.stub
+          # install cloudwatch - issues with Amazon Linux AMI
+          echo 'Amazon Linux AMI' > /etc/issue
+          qs_cloudwatch_install || qs_err
+          # debug cfn-init logs
+          qs_cloudwatch_tracklog /var/log/cfn-init.log
+          qs_cloudwatch_tracklog /var/log/cfn-init-cmd.log
+          # run cfn-init bootstrap
+          cfn-init -v --stack ${AWS::StackName} --resource ChainlinkNodeLaunchConfiguration --configsets ec2_bootstrap --region ${AWS::Region}
 
   ChainlinkNodeInstanceProfile:
     Type: AWS::IAM::InstanceProfile
@@ -639,32 +679,32 @@ Resources:
             Action:
               - sts:AssumeRole
       Path: /
-      ###### added policy to create logs ######
-      # Policies:
-      #   - PolicyName: root
-      #     PolicyDocument:
-      #       Version: 2012-10-17
-      #       Statement:
-      #         - Effect: Allow
-      #           Action:
-      #             - 'logs:CreateLogGroup'
-      #             - 'logs:CreateLogStream'
-      #             - 'logs:PutLogEvents'
-      #             - 'logs:DescribeLogStreams'
-      #           Resource:
-      #             - 'arn:aws:logs:*:*:*'
-      #         - Effect: Allow
-      #           Action:
-      #             - 'cloudwatch:PutMetricData'
-      #             - 'cloudwatch:GetMetricStatistics'
-      #             - 'cloudwatch:ListMetrics'
-      #           Resource:
-      #             - '*'
-      #         - Effect: Allow
-      #           Action:
-      #             - 'ec2:DescribeInstances'
-      #           Resource: '*'
-      ########################################
+      ##### add policy to create logs ######
+      Policies:
+        - PolicyName: root
+          PolicyDocument:
+            Version: 2012-10-17
+            Statement:
+              - Effect: Allow
+                Action:
+                  - 'logs:CreateLogGroup'
+                  - 'logs:CreateLogStream'
+                  - 'logs:PutLogEvents'
+                  - 'logs:DescribeLogStreams'
+                Resource:
+                  - 'arn:aws:logs:*:*:*'
+              - Effect: Allow
+                Action:
+                  - 'cloudwatch:PutMetricData'
+                  - 'cloudwatch:GetMetricStatistics'
+                  - 'cloudwatch:ListMetrics'
+                Resource:
+                  - '*'
+              - Effect: Allow
+                Action:
+                  - 'ec2:DescribeInstances'
+                Resource: '*'
+      #######################################
       ManagedPolicyArns:
         - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore'
         - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
@@ -687,5 +727,5 @@ Resources:
   ChainlinkNodeInitLogGroup:
     Type: 'AWS::Logs::LogGroup'
     Properties:
-      RetentionInDays: 7
       LogGroupName: ChainlinkNodeInitLogGroup
+      RetentionInDays: 7
